


import { Menu } from '../../components/molecules/menu/Menu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], weight:['400', '500', '700', '800','900'] })

export const metadata = {
  title: 'my-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Menu/>
      {children}</body>
    </html>
  )
}
